#
# [config] IMAGE_NAME: "groovenauts/rails-example"
# [config]
# [config] # ビルド前
# [config] BEFORE_BUILD:
# [config]   - abc
# [config]   - def ghi
# [config]
# [config] # ビルド後(失敗時も実行されます)
# [config] AFTER_BUILD:
# [config]   - "jkl"
# [config]   - mno
# [config]
# [config] # ビルド成功時
# [config] ON_BUILD_COMPLETE: foo bar
# [config]
# [config] # 失敗時
# [config] ON_BUILD_ERROR: "baz"
# [config]
#

FROM groovenauts/ruby:2.1.2
MAINTAINER magellan@groovenauts.jp

ENV RAILS_ENV production

# for debug via HTTP dicrectly
EXPOSE 3000

ADD . /usr/src/app
WORKDIR /usr/src/app
VOLUME /usr/src/app/log

RUN bundle install --system

CMD ["bundle", "exec", "rails", "s", "-e", "production"]
