#
# [config] IMAGE_NAME: "groovenauts/rails-example"
# [config] DOCKER_PUSH_COMMAND: "gcloud docker push"
#

FROM groovenauts/ruby:2.1.2
MAINTAINER tech@groovenauts.jp

ENV RAILS_ENV production

# for debug via HTTP dicrectly
EXPOSE 3000

ADD . /usr/src/app
WORKDIR /usr/src/app
VOLUME /usr/src/app/log

RUN bundle install --system

CMD ["bundle", "exec", "rails", "s", "-e", "production"]
